name: Sync master to main

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch and switch to main
        run: |
          git fetch origin
          git checkout -B main origin/main || git checkout -B main

      - name: Clear working directory (exclude .git)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

      - name: Restore content from master (excluding workflows)
        run: |
          git checkout master -- .
          rm -rf .github/workflows
          git add .
          git commit -m "Sync master to main (excluding workflows)" || echo "Nothing to commit"

      - name: Push to main
        run: |
          git push origin main --force
