name: Sync master to main

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push to main
        run: |
          git fetch origin
          git checkout -B main
          git merge master --allow-unrelated-histories -m "Sync master to main"
          git push origin main
